# Generated by Django 5.0 on 2023-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_loaded', models.BooleanField(default=False)),
            ],
        ),
    ]
