# Generated by Django 5.0 on 2023-12-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_api', '0002_apistatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='imgUrl',
            field=models.URLField(blank=True),
        ),
    ]
