# Generated by Django 5.0 on 2023-12-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_api', '0004_alter_character_id_alter_comic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
